(dp1
S'output'
p2
S"<type 'exceptions.SyntaxError'> Invalid URI string in DAL: mysql://:@localhost/"
p3
sS'layer'
p4
S'C:\\Users\\Leandro\\Documents\\CJR\\DIPRO\\PROJETOS\\G\xeanios\\genios\\ProjetoGenios\\web2py\\applications\\Genios\\models\\db.py'
p5
sS'code'
p6
S"db = DAL('mysql://:@localhost/') # Conecta com o banco\n\n\ndb.define_table('pai',Field('nome'),Field('ativo','boolean'),Field('nome','text'),format = '%(nome)s')\ndb.define_table('filho',\n                Field('fk_pai', 'reference pai'),\n                Field('foto','upload', uploadfield='foto_arquivo'),\n                Field('foto_arquivo','blob'),Field('ativo','boolean'),\n                Field('nome'),format = '%(nome)s')\ndb.define_table('pai_x_filho',Field('fk_pai','reference pai'),Field('fk_filho','reference filho') )\n"
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/mdipierro/make_web2py/web2py/gluon/restricted.py", line 220, in restricted\n  File "C:\\Users\\Leandro\\Documents\\CJR\\DIPRO\\PROJETOS\\G\xeanios\\genios\\ProjetoGenios\\web2py\\applications\\Genios\\models\\db.py", line 1, in <module>\n    db = DAL(\'mysql://:@localhost/\') # Conecta com o banco\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 7845, in __init__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 688, in __call__\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 2702, in __init__\nSyntaxError: Invalid URI string in DAL: mysql://:@localhost/\n'
p11
s.