(dp1
S'output'
p2
S'<class \'gluon.contrib.pymysql.err.ProgrammingError\'> (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'int CHAR(1),\\n    PRIMARY KEY (id)\\n) ENGINE=InnoDB CHARACTER SET utf8\' at line 4")'
p3
sS'layer'
p4
S'C:\\Users\\Leandro\\Documents\\CJR\\DIPRO\\PROJETOS\\G\xeanios\\genios\\ProjetoGenios\\web2py\\applications\\Genios\\models\\db.py'
p5
sS'code'
p6
S'db = DAL(\'mysql://root:Ca_784595@localhost/mydb\') # Conecta com o banco\n\n\ndb.define_table(\'pai\',Field(\'nome\'),Field(\'ativo\',\'boolean\'),Field(\'nome\',\'text\'),format = \'%(nome)s\')\ndb.define_table(\'filho\',\n                Field(\'fk_pai\', \'reference pai\'),\n                Field(\'foto\',\'upload\', uploadfield=\'foto_arquivo\'),\n                Field(\'foto_arquivo\',\'blob\'),Field(\'ativo\',\'boolean\'),\n                Field(\'nome\'),format = \'%(nome)s\')\ndb.define_table(\'pai_x_filho\',Field(\'fk_pai\',\'reference pai\'),Field(\'fk_filho\',\'reference filho\') )\n\ndb.define_table(\'perfil\',Field(\'nome\'),Field(\'int\',\'boolean\'))\n\n\ndb.define_table("tb_usuario",\n                Field(\'nome\'),\n                Field(\'fk_id_perfil\',\'reference perfil\'),\n                Field(\'email\'),\n                Field(\'senha\',\'password\'),\n                Field(\'numero_filhos\',\'interger\'),\n                Field(\'ano_escolar\',\'interger\'),\n                Field(\'ativo\',\'interger\'))\n'
p7
sS'snapshot'
p8
(dp9
sS'traceback'
p10
S'Traceback (most recent call last):\n  File "/home/mdipierro/make_web2py/web2py/gluon/restricted.py", line 220, in restricted\n  File "C:\\Users\\Leandro\\Documents\\CJR\\DIPRO\\PROJETOS\\G\xeanios\\genios\\ProjetoGenios\\web2py\\applications\\Genios\\models\\db.py", line 12, in <module>\n    db.define_table(\'perfil\',Field(\'nome\'),Field(\'int\',\'boolean\'))\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 8223, in define_table\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 8260, in lazy_define_table\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 1104, in create_table\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 1950, in create_sequence_and_triggers\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 1969, in execute\n  File "/home/mdipierro/make_web2py/web2py/gluon/dal.py", line 1963, in log_execute\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/cursors.py", line 117, in execute\n  File "/home/mdipierro/make_web2py/web2py/gluon/contrib/pymysql/connections.py", line 202, in defaulterrorhandler\nProgrammingError: (1064, u"You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near \'int CHAR(1),\\n    PRIMARY KEY (id)\\n) ENGINE=InnoDB CHARACTER SET utf8\' at line 4")\n'
p11
s.